name: Environment Demo

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: staging

    steps:
      - name: Exibir vari√°vel de ambiente
        run: echo "Ambiente de deploy: $DEPLOY_ENV"
