name: Secret Demo

on:
  push:

jobs:
  show-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Usando o secret
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo "API_KEY configurado"
